language: nix
jdk:
  - oraclejdk8

stages:
  - name: test

_linux: &linux
  jdk: oraclejdk8
  os: linux

_osx: &osx
  os: osx
  osx_image: xcode7.3

addons:
  apt:
    packages:
      - clang-3.8
      - llvm-3.8
      - clang-format-3.8
      - libc++1
      - libc++-dev

jobs:
  include:
    - stage: build
      <<: *osx
      script: ./tools/bazel run //tasks:ci
    - <<: *linux
      script: ./tools/bazel run //tasks:ci

before_install:
  - git fetch --tags

before_script:
  - nix-env -iA nixpkgs.shellcheck